### ISSUE TITLE
Errors in algorithm package

### ISSUE THREAD

**Issue by andeliero** [NextepDreamTeam/tres#2]
[error] /home/aandelie/IdeaProjects/tres/app/algorithm/AlgorithmService.scala:12: type mismatch;
[error]  found   : Unit
[error]  required: Boolean
[error]   def ready() : Boolean = {}
[error]                           ^
[error] /home/aandelie/IdeaProjects/tres/app/algorithm/Id3.scala:20: only classes can have declared but undefined members
[error]   def entropy()
[error]       ^
[error] two errors found
[error](compile:compileIncremental) Compilation failed
[error] Total time: 4 s, completed 13-nov-2015 15.13.37

**Comment by bsuieric** [comment]
yes boss, i know :( :8ball: :+1:
